name: build

on:
  push:
    branches: [ release, master ]
  pull_request:
    branches: [ release, master ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.r }})
    strategy:
      fail-fast: false
      matrix:
        r: ['release', 'devel']
        config:
          - {os: windows-latest, suffix: 'zip'}
          - {os: macOS-latest, suffix: 'tgz'}
          - {os: ubuntu-20.04, suffix: 'tar.gz', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
        isMaster:
          - ${{ contains(github.ref, 'master') }}
        exclude:
          - isMaster: false
            r: devel
          - isMaster: true
            r: release
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
    
    steps:
      - uses: mikejiang/cyto_build_action@main
        with:
          r-ver: ${{ matrix.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

